<div class="l-footer">
    <div class="row">
        <div class="col-s-12 col-m-12">
            <p>N'hésitez pas à me suivre sur </p>
            <div class="social wow zoomIn">
                <div class="twitter social-img">
                    <a target="_blank" href="https://twitter.com/thomas_batt">
                        <img tooltip="twitter" class="social-icon" ng-src="<?=URL_ASSETS?>img/icons/twitter-over.png" alt="">
                    </a>
                </div>
                <div class="linkedin social-img">
                    <a target="_blank" href="https://www.linkedin.com/in/thomas-batt-601a1a45">
                        <img tooltip="Linkedin" class="social-icon" ng-src="<?=URL_ASSETS?>img/icons/linkedin-over.png" alt="">
                    </a>
                </div>
                <div class="github social-img">
                    <a target="_blank" href="https://github.com/thomasbatt">
                        <img tooltip="Github" class="social-icon" ng-src="<?=URL_ASSETS?>img/icons/github-over.png" alt="">
                    </a>
                </div>            
            </div>
        </div>
        <div class="col-s-12">&copy; Copyright 2016 
            <a target="_blank" href="http://thomasbatt.fr">thomasbatt.fr</a>
            <br>All right reserved
        </div>
    </div>
</div>


