	    <!-- SEO -->
	    <meta name="description" itemprop="description" content="thomas BATT, developpeur intégrateur web sur Strasbourg" />
	    <meta name="keywords" itemprop="keywords" content="developpeur, integrateur, strasbourg, web" />
	    <link rel="canonical" href="index.php" />
	    <meta property="og:title" content="Thomas BATT" />
	    <meta property="og:type" content="cv" />
	    <meta property="og:url" content="index.php" />
	    <meta property="og:image" content="<?=URL_ASSETS?>img/profile-rond.jpg" />
	    <meta property="og:site_name" content="Thomas BATT Developpeur Web" />
	    <meta property="og:description" content="developpeur integrateur sur Strasbourg" />
	    <meta name="twitter:card" content="summary" />
	    <meta name="twitter:title" content="Thomas BATT Developpeur Web" />
	    <meta name="twitter:description" content="developpeur integrateur sur Strasbourg" />
	    <meta name="twitter:image" content="<?=URL_ASSETS?>img/profile-rond.jpg" />
	    <meta itemprop="image" content="<?=URL_ASSETS?>img/profile-rond.jpg" />
	    <!-- /seo -->