<div id="contacter" class="wow fadeInUpBig modal-box <?=htmlentities($display_page['contact'])?> ">
    <header> <a href="#" class="js-modal-close close">×</a>
        <h3>Un projet a me soumettre?</h3>
    </header>
    <div class="modal-body">
        <!-- <strong><span class="titre-article">Un projet a me soumettre?</span></strong> -->
        Contactez moi par mail en remplissant le formulaire ci-dessous.
        <br/>
        <form method="post" id="form" class="form" action="contact" enctype="multipart/form-data" >
            <?php require('views/contact_error.phtml') ?>
            <div class="input input_submit js_submit_contact">
                <input type="hidden" value="send_mail" name="action"/>
                <input type="submit" value="Envoyer" class="submit" />
            </div>
        </form>
    </div>
    <footer> <a href="#" class="btn btn-small js-modal-close">Close</a> </footer>
</div>