<div class="row js-contact-error">
    <div class="col-md-6 col-xs-12 ">
        <div class="b-bottom">
            <div class="label label_name">
                <label for="name">Nom: <span class="required"></span></label>
            </div>
            <div class="input input_name">
                <input class="text" type="text" size="25" value="<?=htmlentities($_SESSION['name'])?>" name="name" id="name" />
            </div>
        </div>
        <?php $pos='1'; require('apps/error.php') ?>
        <div class="b-bottom">
            <div class="label label_email">
                <label for="email">Adresse e-mail: <span class="required"></span></label>
            </div>
            <div class="input input_email">
                <input class="text" type="text" size="15" value="<?=htmlentities($_SESSION['email'])?>" name="email" id="email" />
            </div>
        </div>
        <?php $pos='2'; require('apps/error.php') ?>
        <div class="b-bottom">
            <div class="label label_subject">
                <label for="subject">Sujet: <span class="required"></span></label>
            </div>
            <div class="input input_subject">
                <input class="text" type="text" size="25" value="<?=htmlentities($_SESSION['subject'])?>" name="subject" id="subject" />
            </div>
        </div>
        <?php $pos='3'; require('apps/error.php') ?>
    </div>
    <div class="col-md-6 col-xs-12">
        <div class="b-bottom">
            <div class="label_message">
                <label for="message">Message: <span class="required"></span></label>
            </div>
            <div class="input_message">
                <textarea rows="5" cols="30" name="message" id="message"><?=htmlentities($_SESSION['message'])?></textarea>
            </div>
        </div>
        <?php $pos='4'; require('apps/error.php') ?>
    </div>
</div>