<header class="l-header" parallax-background parallax-ratio="-0.3">
    <section class="main-header home">
        <div class="vertical-container">
            <div class="wrapper clearfix">
                <div class="wow fadeInDown">
                    <h1 id="main-title">Thomas BATT</h1>
                    <h2 id="main-subtitle">Developpeur web</h2>
                </div>
                <div class="wow fadeInUp">
                <nav id="main-nav" role="navigation">
                    <a du-smooth-scroll="nav">Profil</a>
                    <a du-smooth-scroll="nav" href="#competences" class="">Competences</a>
                    <a du-smooth-scroll="nav" href="#projets" class="">Projets</a>
                    <a class="js-open-modal" data-modal-id="contacter" href="<?php URL_WEBSITE ?>">Contact</a>
                </nav>
                </div>
            </div>
        </div>
    </section>
</header>