<header class="l-header" parallax-background parallax-ratio="-0.3">
    <section class="main-header home">
        <div class="vertical-container">
            <div class="wrapper clearfix">
                <div class="wow fadeInDown">
                    <h1 class="main-title">Thomas BATT</h1>
                    <h2 class="main-subtitle">Developpeur web</span></h2>
                </div>
                <div class="wow fadeInUp">
                    <nav class="main-nav" role="navigation">
                        <a du-smooth-scroll="nav">Profil</a>
                        <a du-smooth-scroll="nav" href="#competences" class="">Competences</a>
                        <a du-smooth-scroll="nav" href="#projets" class="">Projets</a>
                        <a class="js-open-contact" href="<?php URL_WEBSITE ?>contact">Contact</a>
                    </nav>
                </div>
                <div class="scrollDownArrow wow fadeInDown">
                    <a du-smooth-scroll="nav"><span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span></a>
                </div>
            </div>
        </div>
    </section>
</header>