<div id="sendmailsuccess" class="wow fadeInUpBig modal-box <?=htmlentities($display_page['sendmailsuccess'])?>">
    <div class="modal-body">
        <div>
            <!-- <strong><span class="titre-article">Un projet a me soumettre?</span></strong> -->
            Votre mail m'a bien été transmis, je vous reponderai des que possible. <br><br>
            Thomas
        </div>
    </div>
    <footer> <a href="#" class="btn btn-small js-modal-close">Close</a> </footer>
</div>