<div class="sendmailsuccess <?=htmlentities($display_page['sendmailsuccess'])?>">
	<div class="contact-body row">
	    <div class="contact-header col-xs-12">
	        <div class="title">Merci, votre mail m'a bien été transmis.</div>
	        <div class="subtitle">je vous reponderai des que possible.</div>
			<div class="button-close ">
				<i class="fa fa-times"></i>
			</div>
	    </div>
	    <div class="contact-content col-xs-12">
			<p>Thomas</p>
	    </div>
	</div>
</div>