<!DOCTYPE html>
<html ng-app="website">

	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1">
	    <title>thomasbatt.fr</title>
	    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans+Caption">
	    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Raleway">
	    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Fenix|Montserrat|Playfair+Display:700italic,400italic' type='text/css'>

	    <link rel="stylesheet" type='text/css' href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css">
	    <!-- <link rel="stylesheet" type='text/css' href="./assets/css/font-awesome.min.css"> -->
	    <link rel="stylesheet" type='text/css' href="./assets/css/devicons.css">
	    <link rel="stylesheet" type='text/css' href="./assets/css/animate.css">
	    <link rel="stylesheet" type='text/css' href="./assets/css/style-contact.css">
	    <link rel="stylesheet" type='text/css' href="./assets/css/style.css">

	    <script type="text/javascript" src="./assets/js/angularjs.js"></script>
	    <Script type="text/javascript" src="./assets/js/wow.min.js"></script>
	    <script type="text/javascript" src="./assets/js/script.js"></script>
	</head>

	<body>
		<?php require('apps/header.php'); ?>

		<?php require('apps/content.php'); ?>

		<?php require('apps/footer.php'); ?>
	</body>
</html>