<!DOCTYPE html>
<html ng-app="website">

	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    
	    <title>thomasbatt.fr</title>
	    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1">
	    <meta name="description" content="site de triathlon de hochfelden">
	    	
	    <!-- SEO -->
	    <meta name="description" itemprop="description" content="thomas BATT, developpeur intégrateur web sur Strasbourg" />
	    <meta name="keywords" itemprop="keywords" content="developpeur, integrateur, strasbourg, web" />
	    <link rel="canonical" href="index.php" />
	    <meta property="og:title" content="Thomas BATT" />
	    <meta property="og:type" content="cv" />
	    <meta property="og:url" content="index.php" />
	    <meta property="og:image" content="<?=URL_IMG_PROFILE?>" />
	    <meta property="og:site_name" content="Thomas BATT Developpeur Web" />
	    <meta property="og:description" content="developpeur integrateur sur Strasbourg" />
	    <meta name="twitter:card" content="summary" />
	    <meta name="twitter:title" content="Thomas BATT Developpeur Web" />
	    <meta name="twitter:description" content="developpeur integrateur sur Strasbourg" />
	    <meta name="twitter:image" content="<?=URL_IMG_PROFILE?>" />
	    <meta itemprop="image" content="<?=URL_IMG_PROFILE?>" />
	    <!-- /seo -->

	    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans+Caption">
	    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Raleway">
	    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Fenix|Montserrat|Playfair+Display:700italic,400italic' type='text/css'>

	    <!-- <link rel="stylesheet" type='text/css' href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css"> -->
	    <link rel="stylesheet" type='text/css' href="./assets/css/font-awesome.min.css">
	    <link rel="stylesheet" type='text/css' href="./assets/css/devicons.css">
	    <link rel="stylesheet" type='text/css' href="./assets/css/animate.css">
	    <link rel="stylesheet" type='text/css' href="./assets/css/style-contact.css">
	    <link rel="stylesheet" type='text/css' href="./assets/css/style.css">

	    <script type="text/javascript" src="./assets/js/angularjs.js"></script>
	    <Script type="text/javascript" src="./assets/js/wow.min.js"></script>
	    <script type="text/javascript" src="./assets/js/script.js"></script>
	</head>

	<body>
		<?php require('apps/header.php'); ?>

		<?php require('apps/content.php'); ?>

		<?php require('apps/footer.php'); ?>
	</body>
</html>