<!DOCTYPE html>
<html ng-app="website">

	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    
	    <title>thomasbatt.fr</title>
	    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1">
	    
	    <?php require("views/seo.phtml") ?>	


	    <link rel="stylesheet" type='text/css' href="./assets/css/app.css">

<!-- 	    <script type="text/javascript" src="./assets/js/angularjs.js"></script>
	    <Script type="text/javascript" src="./assets/js/wow.min.js"></script>
	    <script type="text/javascript" src="./assets/js/script.js"></script> -->
	</head>

	<body>
		<?php require('apps/header.php'); ?>

		<?php require('apps/content.php'); ?>

		<?php require('apps/footer.php'); ?>
	</body>
	   
	<script type="text/javascript" src="./assets/js/app.js"></script>

</html>