<!DOCTYPE html>
<html ng-app="website">
	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <title>thomasbatt.fr</title>
	    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1">
	    <?php require(URL_VIEWS.'components/seo.min.phtml') ?>	
	    <link rel="stylesheet" type='text/css' href="<?=URL_ASSETS?>css/vendors.min.css">
	    <link rel="stylesheet" type='text/css' href="<?=URL_ASSETS?>css/website.min.css">
	</head>
	<body>
		<?php require(URL_APPS.'layout/header.php'); ?>
		<?php require(URL_APPS.'layout/content.php'); ?>
		<?php require(URL_VIEWS.'layout/modals.min.phtml'); ?>
		<?php require(URL_APPS.'layout/footer.php'); ?>
	</body>
		<script type="text/javascript" src="<?=URL_ASSETS?>js/vendors.min.js"></script>
		<script type="text/javascript" src="<?=URL_ASSETS?>js/website.min.js"></script>
</html>